import {DatabaseSync} from 'node:sqlite';
import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {register,reserve,applyPayment,claimBenefit,ballotOpen,castVote,queueReminders,defaults,monthsAfter,member,availability,Fault} from '../lib/platform/core.ts';
import {hash,validSignature} from '../lib/platform/crypto.ts';
import {category,reminderDate} from '../lib/membership.ts';
class DB {
 constructor(){this.sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())this.sql.exec(fs.readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));}
 prepare(sql){const db=this;let args=[];return {bind(...values){args=values;return this;},async first(){return db.sql.prepare(sql).get(...args)||null;},async all(){return {results:db.sql.prepare(sql).all(...args)};},async run(){const r=db.sql.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}};}
 async batch(statements){let release;const previous=this.lock||Promise.resolve();this.lock=new Promise(resolve=>{release=resolve});await previous;this.sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());this.sql.exec('COMMIT');return out;}catch(e){this.sql.exec('ROLLBACK');throw e;}finally{release();}}
}
const user=n=>({id:'phone:+25571234567'+n,phone:'+25571234567'+n,role:'fan',branchId:null});
const admin={id:'admin',phone:null,role:'admin',branchId:null};
const config={...defaults,prices:{Standard:10000,'First 100':50000,Prestige:100000,'Repeated digits':200000}};
async function setup(){const db=new DB();await db.prepare('INSERT INTO settings VALUES(1,?)').bind(JSON.stringify(config)).run();return db;}
async function enroll(db,u,number=88,extra={}){return register(db,u,{name:'Fan '+u.id.slice(-1),number,region:'Dar es Salaam',district:'Ilala',locale:'sw',...extra});}
async function pay(db,u,number=88){const o=await reserve(db,u,number);await applyPayment(db,{eventId:'event:'+o.id,orderId:o.id,amount:o.amount,currency:'TZS',receipt:'receipt:'+o.id},'digest:'+o.id);return o;}
test('number tiers and calendar-month reminders',()=>{assert.equal(category(1),'First 100');assert.equal(category(101),'Prestige');assert.equal(category(222),'Repeated digits');assert.equal(category(1000),'Standard');assert.equal(category(1000000),'Standard');assert.throws(()=>category(0));assert.throws(()=>category(1000001));assert.equal(reminderDate('2027-03-31T10:00:00.000Z'),'2027-02-28T10:00:00.000Z');assert.equal(monthsAfter('2028-01-31T00:00:00.000Z',1),'2028-02-29T00:00:00.000Z');});
test('registration requires verified phone and permanent join rank survives renewals',async()=>{const db=await setup();await assert.rejects(()=>enroll(db,admin),/Verify your phone/);const m=await enroll(db,user(1));assert.equal(m.ordinal,1);const again=await enroll(db,user(1));assert.equal(again.ordinal,1);await pay(db,user(1));assert.equal((await member(db,user(1))).ordinal,1);});
test('number reservation excludes competing buyers and reuses checkout ID',async()=>{const db=await setup();await enroll(db,user(1));await enroll(db,user(2));const o=await reserve(db,user(1),88);assert.equal((await reserve(db,user(1),88)).id,o.id);await assert.rejects(()=>reserve(db,user(2),88),/reserved or assigned/);assert.equal((await availability(db,88)).available,false);});
test('payment validates amount and applies exactly once with one points award',async()=>{const db=await setup();const m=await enroll(db,user(1));const o=await reserve(db,user(1),88);const b={eventId:'e',orderId:o.id,amount:o.amount,currency:'TZS',receipt:'r'};await assert.rejects(()=>applyPayment(db,{...b,amount:1},'d'),/amount/);await applyPayment(db,b,'d');assert.equal((await member(db,user(1))).points,50);assert.equal((await applyPayment(db,b,'d')).duplicate,true);assert.equal((await member(db,user(1))).points,50);assert.equal((await db.prepare('SELECT COUNT(*) n FROM reminders WHERE member_id=?').bind(m.id).first()).n,3);await assert.rejects(()=>applyPayment(db,b,'changed'),/Event ID reused/);});
test('late payment becomes review and never steals a reassigned reservation',async()=>{const db=await setup();await enroll(db,user(1));await enroll(db,user(2));const o=await reserve(db,user(1),88);await db.prepare('UPDATE reservations SET expires=? WHERE order_id=?').bind('2000-01-01',o.id).run();const other=await reserve(db,user(2),88);const r=await applyPayment(db,{eventId:'late',orderId:o.id,amount:o.amount,currency:'TZS',receipt:'late-r'},'d');assert.equal(r.status,'review');assert.equal((await member(db,user(1))).number,null);assert.equal((await db.prepare('SELECT order_id FROM reservations WHERE number=88').first()).order_id,other.id);});
test('expired member can purchase another number without unique-index failure',async()=>{const db=await setup();const m=await enroll(db,user(1));await pay(db,user(1));await db.prepare('UPDATE holdings SET expires=? WHERE member_id=?').bind('2000-01-01',m.id).run();await pay(db,user(1),222);assert.equal((await member(db,user(1))).number,222);assert.equal((await member(db,user(1))).ordinal,1);});
test('benefit claim cannot overspend or debit twice',async()=>{const db=await setup();await enroll(db,user(1));await pay(db,user(1));for(const key of ['b1','b2'])await db.prepare('INSERT INTO benefits VALUES(?,?,?,?,?,?,1)').bind(key,'Offer','Description','Partner',40,'2099-01-01').run();const c=await claimBenefit(db,user(1),'b1');assert.equal((await member(db,user(1))).points,10);assert.equal((await claimBenefit(db,user(1),'b1')).id,c.id);await assert.rejects(()=>claimBenefit(db,user(1),'b2'),/sufficient points/);assert.equal((await member(db,user(1))).points,10);});
test('secret voting freezes eligibility, rejects duplicates, and does not store member with choice',async()=>{const db=await setup();await enroll(db,user(1));await enroll(db,user(2));await pay(db,user(1));const b=await ballotOpen(db,admin,{title:'Leader',region:'Dar es Salaam',district:'Ilala',closes:'2099-01-01',candidates:[{name:'A',bio:'a'},{name:'B',bio:'b'}]});await pay(db,user(2),222);await assert.rejects(()=>castVote(db,user(2),b.id,0),/eligible/);const r=await castVote(db,user(1),b.id,1);assert.ok(r.receipt);await assert.rejects(()=>castVote(db,user(1),b.id,0),/already voted/);const vote=await db.prepare('SELECT * FROM sealed_votes').first();assert.equal(vote.choice,1);assert.ok(!('member_id' in vote));assert.notEqual(vote.id,r.receipt);assert.equal((await db.prepare('SELECT COUNT(*) n FROM sealed_votes').first()).n,1);});
test('inactive membership cannot vote even if eligible at opening',async()=>{const db=await setup();const m=await enroll(db,user(1));await pay(db,user(1));const b=await ballotOpen(db,admin,{title:'Poll',region:'',district:'',closes:'2099-01-01',candidates:[{name:'A',bio:'a'},{name:'B',bio:'b'}]});await db.prepare('UPDATE holdings SET expires=? WHERE member_id=?').bind('2000-01-01',m.id).run();await assert.rejects(()=>castVote(db,user(1),b.id,0),/eligible/);});
test('reminders queue only for current paid ownership and do not duplicate',async()=>{const db=await setup();const m=await enroll(db,user(1));await pay(db,user(1));await db.prepare("UPDATE reminders SET due='2000-01-01' WHERE member_id=?").bind(m.id).run();await queueReminders(db);const first=(await db.prepare('SELECT COUNT(*) n FROM outbox').first()).n;await queueReminders(db);assert.equal((await db.prepare('SELECT COUNT(*) n FROM outbox').first()).n,first);assert.ok(first>=1);});
test('regional ballot excludes members in another region',async()=>{const db=await setup();await enroll(db,user(1),88,{region:'Arusha'});await pay(db,user(1));const b=await ballotOpen(db,admin,{title:'Dar vote',region:'Dar es Salaam',district:'',closes:'2099-01-01',candidates:[{name:'A',bio:'a'},{name:'B',bio:'b'}]});await assert.rejects(()=>castVote(db,user(1),b.id,0),/eligible/);await assert.rejects(()=>ballotOpen(db,user(1),{}),/administrator/);});

test('two simultaneous buyers cannot reserve the same number',async()=>{const db=await setup();await enroll(db,user(1));await enroll(db,user(2));const outcomes=await Promise.allSettled([reserve(db,user(1),88),reserve(db,user(2),88)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal((await db.prepare('SELECT COUNT(*) n FROM reservations').first()).n,1);});
test('signed callback body cannot be changed or verified with another key',async()=>{const secret='test-key',payload='123.body';const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload)))).map(x=>x.toString(16).padStart(2,'0')).join('');assert.equal(await validSignature(secret,signed,payload),true);assert.equal(await validSignature(secret,signed,payload+'x'),false);assert.equal(await validSignature('wrong',signed,payload),false);assert.equal(await validSignature(secret,'invalid',payload),false);assert.equal((await hash('session-token')).length,64);});
test('referral points are awarded only on first paid membership',async()=>{const db=await setup();const ref=await enroll(db,user(1),1000);await enroll(db,user(2),88,{referrer:ref.card_token});await pay(db,user(2));assert.equal((await member(db,user(1))).points,25);await pay(db,user(2));assert.equal((await member(db,user(1))).points,25);assert.equal((await member(db,user(2))).points,100);});
