import {admin,Fault,id,now,member,reserve,applyPayment,auditStmt,type Principal} from './core.ts';
import {hash} from './crypto.ts';
export const clubDefaults={name:'Simba Sports Club',shortName:'Simba',tagline:'Nguvu Moja',about:'',phone:'',email:'',address:'',website:'https://simbasc.co.tz',terms:'',privacy:'',facebook:'',instagram:''};
export async function clubInfo(db:D1Database){const row=await db.prepare('SELECT value FROM club_config WHERE id=1').first<any>();return row?{...clubDefaults,...JSON.parse(row.value)}:clubDefaults;}
export async function createMember(db:D1Database,u:Principal,b:any){admin(u);const principal='phone:'+b.phone;if(await db.prepare('SELECT id FROM members WHERE user_id=? OR phone=?').bind(principal,b.phone).first())throw new Fault(409,'A member with this phone already exists. Search for their profile.');const mid=id();await db.batch([db.prepare('INSERT INTO members VALUES(?,?,?,?,?,?,?)').bind(mid,principal,b.name,b.phone,b.region,b.number,now()),db.prepare('INSERT INTO profiles(member_id,district,locale,card_token) VALUES(?,?,?,?)').bind(mid,b.district,b.locale,id()),db.prepare('INSERT INTO wallets VALUES(?,0)').bind(mid),auditStmt(db,u,'admin-create-member',mid)]);return {id:mid};}
export async function quotePayment(db:D1Database,u:Principal,b:any){admin(u);const m=await db.prepare('SELECT * FROM members WHERE id=?').bind(b.memberId).first<any>();if(!m)throw new Fault(404,'Member not found.');return reserve(db,{id:m.user_id,phone:m.phone,role:'fan',branchId:null},b.number,u);}
export async function recordPayment(db:D1Database,u:Principal,b:any){admin(u);if(Date.parse(b.receivedAt)>Date.now()+60000)throw new Fault(400,'Received date cannot be in the future.');const method=await db.prepare('SELECT * FROM payment_methods WHERE id=? AND active=1').bind(b.methodId).first<any>();if(!method)throw new Fault(400,'Choose an active payment method.');const o=await db.prepare('SELECT * FROM orders WHERE id=?').bind(b.orderId).first<any>();if(!o)throw new Fault(404,'Order not found.');const receipt=b.receipt.trim().toUpperCase();if(await db.prepare('SELECT id FROM orders WHERE receipt=? AND id<>?').bind(receipt,o.id).first())throw new Fault(409,'This transaction reference was already recorded.');
 const event={eventId:'manual:'+o.id,orderId:o.id,receipt,amount:b.amount,currency:'TZS'};
 const digest=await hash(JSON.stringify({...event,methodId:b.methodId,receivedAt:b.receivedAt,note:b.note}));
 const existing=await db.prepare('SELECT digest FROM payment_events WHERE id=?').bind(event.eventId).first<any>();if(existing&&existing.digest!==digest)throw new Fault(409,'This payment was already recorded with different details.');
 if(!existing&&!['reserved','pending'].includes(o.status))throw new Fault(409,'Order is already settled.');
 return applyPayment(db,event,digest,{actor:u,methodId:method.id,methodName:method.name,receivedAt:b.receivedAt,note:b.note});
}
export async function recordRefund(db:D1Database,u:Principal,b:any){admin(u);const o=await db.prepare('SELECT * FROM orders WHERE id=?').bind(b.orderId).first<any>();if(!o||o.status!=='review')throw new Fault(409,'Only unresolved payments awaiting review can be marked refunded.');const reference=b.reference.trim().toUpperCase();await db.batch([db.prepare("INSERT INTO refund_records SELECT id,?,?,?,? FROM orders WHERE id=? AND status='review'").bind(reference,b.note,u.id,now(),o.id),db.prepare("UPDATE orders SET status='refunded' WHERE id=? AND status='review'").bind(o.id),auditStmt(db,u,'external-refund-recorded',o.id)]);return {ok:true};}
export async function updateMember(db:D1Database,u:Principal,b:any){admin(u);if(!await db.prepare('SELECT id FROM members WHERE id=?').bind(b.id).first())throw new Fault(404,'Member not found.');await db.batch([db.prepare('UPDATE members SET name=?,region=? WHERE id=?').bind(b.name,b.region,b.id),db.prepare('UPDATE profiles SET district=?,locale=? WHERE member_id=?').bind(b.district,b.locale,b.id),auditStmt(db,u,'update-member',b.id)]);return {ok:true};}
