import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const members=sqliteTable('members',{id:text('id').primaryKey(),userId:text('user_id').notNull().unique(),name:text('name').notNull(),phone:text('phone').notNull(),region:text('region').notNull(),requestedNumber:integer('requested_number').notNull(),created:text('created').notNull()});
export const holdings=sqliteTable('holdings',{number:integer('number').primaryKey(),memberId:text('member_id').notNull().unique(),expires:text('expires').notNull(),paidAt:text('paid_at').notNull()});
export const ballots=sqliteTable('ballots',{id:text('id').primaryKey(),title:text('title').notNull(),region:text('region'),options:text('options').notNull(),opens:text('opens').notNull(),closes:text('closes').notNull()});
export const votes=sqliteTable('votes',{id:text('id').primaryKey(),ballotId:text('ballot_id').notNull(),memberId:text('member_id').notNull(),choice:integer('choice').notNull(),created:text('created').notNull()},t=>[uniqueIndex('one_vote').on(t.ballotId,t.memberId)]);
export const eligibility=sqliteTable('eligibility',{id:text('id').primaryKey(),ballotId:text('ballot_id').notNull(),memberId:text('member_id').notNull()},t=>[uniqueIndex('one_eligible').on(t.ballotId,t.memberId)]);
export const reminders=sqliteTable('reminders',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),expiry:text('expiry').notNull(),due:text('due').notNull(),status:text('status').notNull().default('pending')});

// Membership expansion: existing migration remains immutable.
export const profiles=sqliteTable('profiles',{ordinal:integer('ordinal').primaryKey({autoIncrement:true}),memberId:text('member_id').notNull().unique(),district:text('district').notNull().default(''),locale:text('locale').notNull().default('sw'),verifiedPhone:text('verified_phone').unique(),referrer:text('referrer'),cardToken:text('card_token').notNull().unique()});
export const sessions=sqliteTable('sessions',{hash:text('hash').primaryKey(),principal:text('principal').notNull(),phone:text('phone').notNull(),expires:text('expires').notNull()});
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const settings=sqliteTable('settings',{id:integer('id').primaryKey(),value:text('value').notNull()});
export const branches=sqliteTable('branches',{id:text('id').primaryKey(),name:text('name').notNull(),region:text('region').notNull(),district:text('district').notNull().default('')},t=>[uniqueIndex('branch_region_district').on(t.region,t.district)]);
export const roles=sqliteTable('roles',{principal:text('principal').primaryKey(),role:text('role').notNull(),branchId:text('branch_id')});
export const announcements=sqliteTable('announcements',{id:text('id').primaryKey(),title:text('title').notNull(),body:text('body').notNull(),branchId:text('branch_id'),created:text('created').notNull()});
export const reservations=sqliteTable('reservations',{number:integer('number').primaryKey(),memberId:text('member_id').notNull().unique(),orderId:text('order_id').notNull(),expires:text('expires').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),number:integer('number').notNull(),amount:integer('amount').notNull(),currency:text('currency').notNull(),expires:text('expires').notNull(),status:text('status').notNull(),created:text('created').notNull(),providerRef:text('provider_ref').unique(),receipt:text('receipt').unique(),paidAt:text('paid_at')},t=>[index('orders_member_created').on(t.memberId,t.created)]);
export const paymentEvents=sqliteTable('payment_events',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),digest:text('digest').notNull(),created:text('created').notNull()});
export const waitlist=sqliteTable('waitlist',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),number:integer('number').notNull(),created:text('created').notNull(),notified:text('notified')},t=>[uniqueIndex('waitlist_member_number').on(t.memberId,t.number)]);
export const wallets=sqliteTable('wallets',{memberId:text('member_id').primaryKey(),points:integer('points').notNull().default(0)});
export const points=sqliteTable('points',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),amount:integer('amount').notNull(),reason:text('reason').notNull(),created:text('created').notNull()},t=>[index('points_member').on(t.memberId)]);
export const benefits=sqliteTable('benefits',{id:text('id').primaryKey(),title:text('title').notNull(),description:text('description').notNull(),partner:text('partner').notNull(),cost:integer('cost').notNull().default(0),expires:text('expires').notNull(),active:integer('active').notNull().default(1)});
export const claims=sqliteTable('claims',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),benefitId:text('benefit_id').notNull(),created:text('created').notNull(),usedAt:text('used_at')},t=>[uniqueIndex('one_benefit_claim').on(t.memberId,t.benefitId)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),title:text('title').notNull(),venue:text('venue').notNull(),starts:text('starts').notNull(),ends:text('ends').notNull(),branchId:text('branch_id'),points:integer('points').notNull().default(10)});
export const attendance=sqliteTable('attendance',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),eventId:text('event_id').notNull(),created:text('created').notNull()},t=>[uniqueIndex('one_checkin').on(t.memberId,t.eventId)]);
export const ballotDetails=sqliteTable('ballot_details',{ballotId:text('ballot_id').primaryKey(),district:text('district'),candidates:text('candidates').notNull()});
export const participation=sqliteTable('participation',{id:text('id').primaryKey(),ballotId:text('ballot_id').notNull(),memberId:text('member_id').notNull()},t=>[uniqueIndex('one_secret_vote').on(t.ballotId,t.memberId)]);
export const sealedVotes=sqliteTable('sealed_votes',{id:text('id').primaryKey(),ballotId:text('ballot_id').notNull(),choice:integer('choice').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),created:text('created').notNull()});
export const outbox=sqliteTable('outbox',{id:text('id').primaryKey(),memberId:text('member_id').notNull(),kind:text('kind').notNull(),body:text('body').notNull(),status:text('status').notNull().default('pending'),claimUntil:text('claim_until'),providerId:text('provider_id'),created:text('created').notNull()});

export const clubConfig=sqliteTable('club_config',{id:integer('id').primaryKey(),value:text('value').notNull()});
export const paymentMethods=sqliteTable('payment_methods',{id:text('id').primaryKey(),name:text('name').notNull(),kind:text('kind').notNull(),accountName:text('account_name').notNull(),accountNumber:text('account_number').notNull(),instructions:text('instructions').notNull(),active:integer('active').notNull().default(1)});
export const manualPayments=sqliteTable('manual_payments',{orderId:text('order_id').primaryKey(),methodId:text('method_id').notNull(),methodName:text('method_name').notNull(),receivedAt:text('received_at').notNull(),note:text('note').notNull(),actor:text('actor').notNull()});
export const refundRecords=sqliteTable('refund_records',{orderId:text('order_id').primaryKey(),reference:text('reference').notNull().unique(),note:text('note').notNull(),actor:text('actor').notNull(),created:text('created').notNull()});
export const clubPosts=sqliteTable('club_posts',{id:text('id').primaryKey(),title:text('title').notNull(),body:text('body').notNull(),url:text('url').notNull(),published:integer('published').notNull().default(0),created:text('created').notNull()});
