import {clubInfo} from '@/lib/platform/admin';
import {database} from '@/lib/server-db';
import {Fault,now,id,config,member,needMember,admin,sameOrigin,auditStmt,register,availability,reserve,claimBenefit,ballotOpen,castVote,listBallots} from '@/lib/platform/core';
import {current,requireUser,limit,signIn,signOut} from '@/lib/platform/security';
import {capabilities,otp,paymentRequest} from '@/lib/platform/providers';
import {actions} from '@/lib/platform/validation';
import {regions} from '@/lib/membership';
export const dynamic='force-dynamic';
function reply(value:any,status=200){return Response.json(value,{status,headers:{'Cache-Control':'no-store'}});}
function error(e:any){if(e instanceof Fault)return reply({error:e.message},e.status);if(e?.name==='ZodError')return reply({error:e.issues.map((x:any)=>x.message).join(' ')},400);console.error('Platform request failed',e?.message);return reply({error:'This action could not be completed. Please retry.'},503);}
export async function GET(req:Request){try{const db=database(),u=await current(db),q=new URL(req.url).searchParams,r=q.get('resource')||'home';
 if(r==='availability')return reply(await availability(db,Number(q.get('number'))));
 if(r==='verify-claim'){if(!u||!['admin','scanner'].includes(u.role))throw new Fault(403,'Scanner access required.');const claim=await db.prepare(`SELECT c.id,c.used_at,b.title,b.partner,b.expires,CASE WHEN h.expires>? AND b.expires>? AND b.active=1 AND c.used_at IS NULL THEN 1 ELSE 0 END AS valid FROM claims c JOIN benefits b ON b.id=c.benefit_id LEFT JOIN holdings h ON h.member_id=c.member_id WHERE c.id=?`).bind(now(),now(),q.get('token')||'').first();if(!claim)throw new Fault(404,'Claim not found.');return reply(claim);}
 if(r==='verify'){const token=q.get('token')||'';if(!/^[a-f0-9-]{36}$/.test(token))throw new Fault(400,'Invalid card');const m=await db.prepare(`SELECT m.name,m.region,p.ordinal,h.number,h.expires FROM profiles p JOIN members m ON m.id=p.member_id LEFT JOIN holdings h ON h.member_id=m.id AND h.expires>? WHERE p.card_token=?`).bind(now(),token).first<any>();if(!m)throw new Fault(404,'Card not found.');return reply({valid:!!m.number,number:m.number,expires:m.expires,region:m.region,initials:m.name.split(' ').map((x:string)=>x[0]).join('')});}
 if(r==='home'){const m=u?await member(db,u):null;const branches=(await db.prepare('SELECT * FROM branches ORDER BY region,district,name').all()).results;
 return reply({club:await clubInfo(db),paymentMethods:(await db.prepare('SELECT * FROM payment_methods WHERE active=1 ORDER BY name').all()).results,posts:(await db.prepare('SELECT * FROM club_posts WHERE published=1 ORDER BY created DESC LIMIT 50').all()).results,user:u,member:m,config:await config(db),capabilities:capabilities(),regions,branches,benefits:(await db.prepare('SELECT * FROM benefits WHERE active=1 AND expires>? ORDER BY expires').bind(now()).all()).results,events:(await db.prepare('SELECT * FROM events WHERE ends>? ORDER BY starts').bind(now()).all()).results,announcements:(await db.prepare('SELECT a.*,b.name AS branch_name FROM announcements a LEFT JOIN branches b ON b.id=a.branch_id ORDER BY created DESC LIMIT 50').all()).results,ballots:await listBallots(db,u),orders:m?(await db.prepare('SELECT * FROM orders WHERE member_id=? ORDER BY created DESC LIMIT 30').bind(m.id).all()).results:[],waitlist:m?(await db.prepare('SELECT * FROM waitlist WHERE member_id=?').bind(m.id).all()).results:[],claims:m?(await db.prepare('SELECT c.*,b.title,b.partner,b.expires FROM claims c JOIN benefits b ON b.id=c.benefit_id WHERE member_id=?').bind(m.id).all()).results:[],points:m?(await db.prepare('SELECT * FROM points WHERE member_id=? ORDER BY created DESC LIMIT 50').bind(m.id).all()).results:[]});}
 if(r==='admin'){if(!u)throw new Fault(401,'Sign in first.');admin(u);return reply({members:(await db.prepare(`SELECT m.id,m.name,m.region,m.phone,m.user_id,p.ordinal,p.district,h.number,h.expires FROM members m LEFT JOIN profiles p ON p.member_id=m.id LEFT JOIN holdings h ON h.member_id=m.id ORDER BY m.created DESC LIMIT 500`).all()).results,totals:await db.prepare(`SELECT (SELECT COUNT(*) FROM members) AS members,(SELECT COUNT(*) FROM holdings WHERE expires>?) AS active,(SELECT COALESCE(SUM(amount),0) FROM orders WHERE status='paid') AS revenue,(SELECT COUNT(*) FROM orders WHERE status='review') AS review,(SELECT COUNT(*) FROM holdings WHERE expires>? AND expires<=?) AS expiring`).bind(now(),now(),new Date(Date.now()+30*86400000).toISOString()).first(),regional:(await db.prepare(`SELECT m.region,COUNT(*) AS members,SUM(CASE WHEN h.expires>? THEN 1 ELSE 0 END) AS active FROM members m LEFT JOIN holdings h ON h.member_id=m.id GROUP BY m.region`).bind(now()).all()).results,orders:(await db.prepare('SELECT o.*,m.name FROM orders o JOIN members m ON m.id=o.member_id ORDER BY created DESC LIMIT 100').all()).results,roles:(await db.prepare('SELECT * FROM roles').all()).results,audit:(await db.prepare('SELECT * FROM audit ORDER BY created DESC LIMIT 100').all()).results,outbox:(await db.prepare('SELECT id,kind,status,created,provider_id FROM outbox ORDER BY created DESC LIMIT 100').all()).results});}
 if(r==='branch-dashboard'){if(!u||!['admin','leader'].includes(u.role))throw new Fault(403,'Branch leader access required.');const branch=await db.prepare('SELECT * FROM branches WHERE id=?').bind(u.role==='admin'?(q.get('id')||''):u.branchId).first<any>();if(!branch)throw new Fault(404,'No branch assigned.');return reply({branch,totals:await db.prepare(`SELECT COUNT(*) AS members,SUM(CASE WHEN h.expires>? THEN 1 ELSE 0 END) AS active FROM members m JOIN profiles p ON p.member_id=m.id LEFT JOIN holdings h ON h.member_id=m.id WHERE m.region=? AND (?='' OR p.district=?)`).bind(now(),branch.region,branch.district,branch.district).first(),collections:await db.prepare(`SELECT COALESCE(SUM(o.amount),0) AS amount FROM orders o JOIN members m ON m.id=o.member_id JOIN profiles p ON p.member_id=m.id WHERE o.status='paid' AND m.region=? AND (?='' OR p.district=?)`).bind(branch.region,branch.district,branch.district).first()});}
 throw new Fault(404,'Unknown resource');}catch(e){return error(e);}}
export async function POST(req:Request){try{sameOrigin(req);if(Number(req.headers.get('content-length')||0)>30000)throw new Fault(413,'Request too large.');const rawText=await req.text();if(rawText.length>30000)throw new Fault(413,'Request too large.');const raw:any=JSON.parse(rawText),action=raw.action as keyof typeof actions;if(!actions[action])throw new Fault(400,'Unknown action');const b:any=actions[action].parse(raw),db=database();
 if(action==='otp-send'||action==='otp-check'){await limit(db,action+':phone:'+b.phone,action==='otp-send'?3:8,600);await limit(db,action+':ip:'+(req.headers.get('cf-connecting-ip')||'unknown'),20,600);const result=await otp(b.phone,action==='otp-check'?b.code:undefined);if(action==='otp-check'){if(result.status!=='approved')throw new Fault(400,'Incorrect or expired code.');await signIn(db,b.phone);}return reply({ok:true});}
 if(action==='logout'){await signOut(db);return reply({ok:true});}
 const u=await requireUser(db);
 if(action==='register')return reply({member:await register(db,u,b)});
 if(action==='preferences'){const m=await needMember(db,u);await db.prepare('UPDATE profiles SET locale=? WHERE member_id=?').bind(b.locale,m.id).run();return reply({ok:true});}
 if(action==='checkout'){if(!capabilities().payments)throw new Fault(503,'Mobile-money payments are awaiting provider setup.');await limit(db,'checkout:'+u.id,10,600);const m=await needMember(db,u),o=await reserve(db,u,b.number);const ref=await paymentRequest(o,m.phone,new URL(req.url).origin);await db.prepare("UPDATE orders SET provider_ref=?,status='pending' WHERE id=? AND status IN ('reserved','pending')").bind(ref,o.id).run();return reply({order:o,message:'Payment request sent. Approve on your phone. Membership activates only after confirmation.'});}
 if(action==='waitlist'){const m=await needMember(db,u);await db.prepare('INSERT OR IGNORE INTO waitlist(id,member_id,number,created) VALUES(?,?,?,?)').bind(id(),m.id,b.number,now()).run();return reply({ok:true});}
 if(action==='leave-waitlist'){const m=await needMember(db,u);await db.prepare('DELETE FROM waitlist WHERE id=? AND member_id=?').bind(b.id,m.id).run();return reply({ok:true});}
 if(action==='claim-benefit')return reply({claim:await claimBenefit(db,u,b.id)});
 if(action==='vote')return reply(await castVote(db,u,b.id,b.choice));
 if(action==='announcement'||action==='event'){if(!['admin','leader'].includes(u.role))throw new Fault(403,'Staff access required.');if(u.role==='leader'&&(!u.branchId||b.branchId!==u.branchId))throw new Fault(403,'You can only publish for your assigned branch.');if(b.branchId&&!await db.prepare('SELECT id FROM branches WHERE id=?').bind(b.branchId).first())throw new Fault(400,'Unknown branch');const key=id();await db.batch([action==='announcement'?db.prepare('INSERT INTO announcements VALUES(?,?,?,?,?)').bind(key,b.title,b.body,b.branchId||null,now()):db.prepare('INSERT INTO events VALUES(?,?,?,?,?,?,?)').bind(key,b.title,b.venue,b.starts,b.ends,b.branchId||null,b.points),auditStmt(db,u,action,key)]);return reply({id:key});}
 if(action==='check-in'||action==='redeem'){if(!['admin','scanner','leader'].includes(u.role))throw new Fault(403,'Scanner access required.');if(action==='redeem'){if(u.role!=='admin'&&u.role!=='scanner')throw new Fault(403,'Club scanner access required.');const result=await db.prepare(`UPDATE claims SET used_at=? WHERE id=? AND used_at IS NULL AND EXISTS(SELECT 1 FROM benefits b WHERE b.id=claims.benefit_id AND b.expires>? AND b.active=1) AND EXISTS(SELECT 1 FROM holdings h WHERE h.member_id=claims.member_id AND h.expires>?) RETURNING id`).bind(now(),b.token,now(),now()).first();if(!result)throw new Fault(409,'Claim is invalid, expired or already redeemed.');await auditStmt(db,u,'redeem',b.token).run();return reply({ok:true});}
 const ev=await db.prepare('SELECT * FROM events WHERE id=? AND starts<=? AND ends>?').bind(b.eventId,now(),now()).first<any>();if(!ev)throw new Fault(409,'Check-in is only available during the event.');if(u.role==='leader'&&ev.branch_id!==u.branchId)throw new Fault(403,'This event belongs to another branch.');const mid=await db.prepare('SELECT member_id FROM profiles WHERE card_token=?').bind(b.cardToken).first<any>();if(!mid)throw new Fault(404,'Card not found');const aid=id(),time=now();const r=await db.batch([db.prepare('INSERT OR IGNORE INTO attendance SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM holdings WHERE member_id=? AND expires>?)').bind(aid,mid.member_id,ev.id,time,mid.member_id,time),db.prepare('INSERT INTO points SELECT ?,member_id,?,?,created FROM attendance WHERE id=?').bind('attendance:'+aid,ev.points,'Event attendance',aid),db.prepare('UPDATE wallets SET points=COALESCE((SELECT SUM(amount) FROM points WHERE points.member_id=wallets.member_id),0) WHERE member_id=?').bind(mid.member_id),auditStmt(db,u,'check-in',ev.id)]);if(!r[0].meta.changes)throw new Fault(409,'Already checked in, or membership is inactive.');return reply({ok:true});}
 admin(u);
 if(action==='settings'){await db.batch([db.prepare('INSERT INTO settings VALUES(1,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind(JSON.stringify(b)),auditStmt(db,u,'settings','membership')]);return reply({ok:true});}
 if(action==='branch'){const exists=await db.prepare('SELECT id FROM branches WHERE region=? AND district=?').bind(b.region,b.district).first();if(exists)throw new Fault(409,'A branch already exists for this region and district.');const key=id();await db.batch([db.prepare('INSERT INTO branches VALUES(?,?,?,?)').bind(key,b.name,b.region,b.district),auditStmt(db,u,'branch',key)]);return reply({id:key});}
 if(action==='role'){if(b.role==='leader'&&!b.branchId)throw new Fault(400,'Select the leader’s branch.');if(b.branchId&&!await db.prepare('SELECT id FROM branches WHERE id=?').bind(b.branchId).first())throw new Fault(400,'Unknown branch');await db.batch([db.prepare('INSERT INTO roles VALUES(?,?,?) ON CONFLICT(principal) DO UPDATE SET role=excluded.role,branch_id=excluded.branch_id').bind(b.principal,b.role,b.branchId||null),auditStmt(db,u,'role',b.principal)]);return reply({ok:true});}
 if(action==='benefit'){if(b.expires<=now())throw new Fault(400,'Expiry must be in the future.');const key=id();await db.batch([db.prepare('INSERT INTO benefits VALUES(?,?,?,?,?,?,1)').bind(key,b.title,b.description,b.partner,b.cost,b.expires),auditStmt(db,u,'benefit',key)]);return reply({id:key});}
 if(action==='disable-benefit'){await db.batch([db.prepare('UPDATE benefits SET active=0 WHERE id=?').bind(b.id),auditStmt(db,u,'disable-benefit',b.id)]);return reply({ok:true});}
 if(action==='ballot')return reply(await ballotOpen(db,u,b));
 throw new Fault(400,'Unsupported action');}catch(e){return error(e);}}
