import {database} from '@/lib/server-db';
import {requireUser} from '@/lib/platform/security';
import {admin,Fault,now,id,config,sameOrigin,auditStmt,listBallots} from '@/lib/platform/core';
import {clubInfo,createMember,updateMember,quotePayment,recordPayment,recordRefund} from '@/lib/platform/admin';
import {adminActions} from '@/lib/platform/admin-validation';
import {capabilities} from '@/lib/platform/providers';
import {regions} from '@/lib/membership';
export const dynamic='force-dynamic';
const reply=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
function error(e:any){if(e instanceof Fault)return reply({error:e.message},e.status);if(e.name==='ZodError')return reply({error:e.issues.map((i:any)=>i.message).join(' ')},400);if(e instanceof SyntaxError)return reply({error:'Invalid request.'},400);if(String(e.message).includes('UNIQUE constraint'))return reply({error:'This record already exists. Refresh before retrying.'},409);console.error('Admin operation failed',e.message);return reply({error:'Could not complete the action. Your input has been kept; please retry.'},503);}
const pageSize=25;
export async function GET(req:Request){try{const db=database(),u=await requireUser(db);admin(u);const q=new URL(req.url).searchParams,r=q.get('resource')||'overview',time=now();const page=Math.max(1,Math.min(100000,Number(q.get('page'))||1)),offset=(Math.floor(page)-1)*pageSize;
 if(r==='overview')return reply({user:u,config:await config(db),club:await clubInfo(db),capabilities:capabilities(),regions,methods:(await db.prepare('SELECT * FROM payment_methods ORDER BY name').all()).results,branches:(await db.prepare('SELECT * FROM branches ORDER BY region,district,name').all()).results,totals:await db.prepare(`SELECT (SELECT COUNT(*) FROM members) members,(SELECT COUNT(*) FROM holdings WHERE expires>?) active,(SELECT COALESCE(SUM(amount),0) FROM orders WHERE status='paid') revenue,(SELECT COALESCE(SUM(amount),0) FROM orders WHERE status='review') reviewAmount,(SELECT COUNT(*) FROM orders WHERE status='review') review,(SELECT COUNT(*) FROM holdings WHERE expires>? AND expires<=?) expiring`).bind(time,time,new Date(Date.now()+30*86400000).toISOString()).first(),regional:(await db.prepare(`SELECT m.region,COUNT(*) members,SUM(CASE WHEN h.expires>? THEN 1 ELSE 0 END) active FROM members m LEFT JOIN holdings h ON h.member_id=m.id GROUP BY m.region ORDER BY members DESC`).bind(time).all()).results,recent:(await db.prepare('SELECT * FROM audit ORDER BY created DESC LIMIT 8').all()).results});
 if(r==='members'){const search='%'+(q.get('q')||'').slice(0,100)+'%',region=q.get('region')||'',status=q.get('status')||'';const from=`FROM members m LEFT JOIN profiles p ON p.member_id=m.id LEFT JOIN holdings h ON h.member_id=m.id WHERE (m.name LIKE ? OR m.phone LIKE ? OR m.id LIKE ? OR CAST(h.number AS TEXT) LIKE ?) AND (?='' OR m.region=?) AND (?='' OR (?='active' AND h.expires>?) OR (?='inactive' AND (h.expires IS NULL OR h.expires<=?)))`;const args=[search,search,search,search,region,region,status,status,time,status,time];return reply({rows:(await db.prepare(`SELECT m.*,p.ordinal,p.district,p.locale,p.verified_phone,h.number,h.expires,CASE WHEN h.expires>? THEN 'active' ELSE 'inactive' END status ${from} ORDER BY m.created DESC,m.id LIMIT ? OFFSET ?`).bind(time,...args,pageSize,offset).all()).results,total:(await db.prepare(`SELECT COUNT(*) count ${from}`).bind(...args).first<any>()).count,page});}
 if(r==='member'){const mid=q.get('id')||'';const m=await db.prepare('SELECT m.*,p.ordinal,p.district,p.locale,p.verified_phone,h.number,h.expires,w.points FROM members m LEFT JOIN profiles p ON p.member_id=m.id LEFT JOIN holdings h ON h.member_id=m.id LEFT JOIN wallets w ON w.member_id=m.id WHERE m.id=?').bind(mid).first();if(!m)throw new Fault(404,'Member not found.');return reply({member:m,orders:(await db.prepare('SELECT * FROM orders WHERE member_id=? ORDER BY created DESC LIMIT 50').bind(mid).all()).results});}
 if(r==='payments'){const search='%'+(q.get('q')||'').slice(0,100)+'%',status=q.get('status')||'';const from=`FROM orders o JOIN members m ON m.id=o.member_id LEFT JOIN manual_payments p ON p.order_id=o.id LEFT JOIN refund_records f ON f.order_id=o.id WHERE (m.name LIKE ? OR m.phone LIKE ? OR COALESCE(o.receipt,'') LIKE ? OR o.id LIKE ?) AND (?='' OR o.status=?)`;const args=[search,search,search,search,status,status];return reply({rows:(await db.prepare(`SELECT o.*,m.name,m.phone,p.method_name,p.received_at,p.note,p.actor,f.reference refund_reference,f.note refund_note ${from} ORDER BY o.created DESC,o.id LIMIT ? OFFSET ?`).bind(...args,pageSize,offset).all()).results,total:(await db.prepare(`SELECT COUNT(*) count ${from}`).bind(...args).first<any>()).count,page});}
 if(r==='ballots')return reply({rows:await listBallots(db,u),turnout:(await db.prepare('SELECT ballot_id,COUNT(*) count FROM participation GROUP BY ballot_id').all()).results});
 if(r==='announcements')return reply({rows:(await db.prepare('SELECT * FROM announcements ORDER BY created DESC LIMIT 200').all()).results});
 if(r==='events')return reply({rows:(await db.prepare('SELECT e.*,(SELECT COUNT(*) FROM attendance a WHERE a.event_id=e.id) attendees FROM events e ORDER BY starts DESC LIMIT 200').all()).results});
 if(r==='benefits')return reply({rows:(await db.prepare('SELECT b.*,(SELECT COUNT(*) FROM claims c WHERE c.benefit_id=b.id) claims FROM benefits b ORDER BY expires DESC LIMIT 200').all()).results});
 if(r==='posts')return reply({rows:(await db.prepare('SELECT * FROM club_posts ORDER BY created DESC LIMIT 200').all()).results});
 if(r==='staff')return reply({rows:(await db.prepare('SELECT r.*,m.name,m.phone,b.name branch_name FROM roles r LEFT JOIN members m ON m.user_id=r.principal LEFT JOIN branches b ON b.id=r.branch_id ORDER BY r.role,r.principal').all()).results});
 if(r==='audit'||r==='notifications'){const table=r==='audit'?'audit':'outbox';return reply({rows:(await db.prepare(`SELECT * FROM ${table} ORDER BY created DESC,id LIMIT ? OFFSET ?`).bind(pageSize,offset).all()).results,total:(await db.prepare(`SELECT COUNT(*) count FROM ${table}`).first<any>()).count,page});}
 throw new Fault(404,'Unknown resource.');}catch(e){return error(e);}}
export async function POST(req:Request){try{sameOrigin(req);const db=database(),u=await requireUser(db);admin(u);const raw=await req.text();if(raw.length>50000)throw new Fault(413,'Request too large.');const input=JSON.parse(raw),action=input.action as keyof typeof adminActions;if(!adminActions[action])throw new Fault(400,'Unknown action.');const b:any=adminActions[action].parse(input);
 if(action==='create-member')return reply(await createMember(db,u,b));if(action==='update-member')return reply(await updateMember(db,u,b));if(action==='quote-payment')return reply(await quotePayment(db,u,b));if(action==='record-payment')return reply(await recordPayment(db,u,b));if(action==='record-refund')return reply(await recordRefund(db,u,b));
 if(action==='club'){await db.batch([db.prepare('INSERT INTO club_config VALUES(1,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind(JSON.stringify(b)),auditStmt(db,u,'update-club','club')]);return reply({ok:true});}
 if(action==='payment-method'){const key=b.id||id();await db.batch([db.prepare('INSERT INTO payment_methods VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,kind=excluded.kind,account_name=excluded.account_name,account_number=excluded.account_number,instructions=excluded.instructions,active=excluded.active').bind(key,b.name,b.kind,b.accountName,b.accountNumber,b.instructions,b.active?1:0),auditStmt(db,u,'save-payment-method',key)]);return reply({id:key});}
 if(action==='post'){const key=b.id||id();await db.batch([db.prepare('INSERT INTO club_posts VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,url=excluded.url,published=excluded.published').bind(key,b.title,b.body,b.url,b.published?1:0,now()),auditStmt(db,u,'save-club-post',key)]);return reply({id:key});}
 if('branchId' in b&&b.branchId&&!await db.prepare('SELECT id FROM branches WHERE id=?').bind(b.branchId).first())throw new Fault(400,'Unknown branch.');
 let statement:D1PreparedStatement;
 if(action==='staff-role'){if(b.principal===u.id)throw new Fault(409,'Ask another administrator to change your own role.');if(!/^(phone:\+255[67]\d{8}|[a-zA-Z0-9_-]+)$/.test(b.principal))throw new Fault(400,'Use an account ID or phone:+255… identity.');if(b.role==='leader'&&!b.branchId)throw new Fault(400,'Choose a branch for this leader.');statement=db.prepare('INSERT INTO roles VALUES(?,?,?) ON CONFLICT(principal) DO UPDATE SET role=excluded.role,branch_id=excluded.branch_id').bind(b.principal,b.role,b.role==='leader'?b.branchId:null);}
 else if(action==='announcement-edit')statement=db.prepare('UPDATE announcements SET title=?,body=?,branch_id=? WHERE id=?').bind(b.title,b.body,b.branchId||null,b.id);
 else if(action==='announcement-delete')statement=db.prepare('DELETE FROM announcements WHERE id=?').bind(b.id);
 else if(action==='branch-edit')statement=db.prepare('UPDATE branches SET name=?,region=?,district=? WHERE id=?').bind(b.name,b.region,b.district,b.id);
 else if(action==='event-edit'){const old=await db.prepare('SELECT points,starts FROM events WHERE id=?').bind(b.id).first<any>();if(old&&old.starts<=now())throw new Fault(409,'An event that has started cannot be edited.');statement=db.prepare('UPDATE events SET title=?,venue=?,starts=?,ends=?,branch_id=?,points=? WHERE id=?').bind(b.title,b.venue,b.starts,b.ends,b.branchId||null,b.points,b.id);}
 else if(action==='benefit-edit'){const count=await db.prepare('SELECT COUNT(*) count FROM claims WHERE benefit_id=?').bind(b.id).first<any>();if(count.count){const old=await db.prepare('SELECT cost,expires FROM benefits WHERE id=?').bind(b.id).first<any>();if(b.cost!==old.cost||b.expires!==old.expires)throw new Fault(409,'Claimed benefits keep their original points cost and expiry. You can edit their description or disable them.');}statement=db.prepare('UPDATE benefits SET title=?,description=?,partner=?,cost=?,expires=?,active=? WHERE id=?').bind(b.title,b.description,b.partner,b.cost,b.expires,b.active?1:0,b.id);}
 else if(action==='close-ballot'){statement=db.prepare('UPDATE ballots SET closes=? WHERE id=? AND closes>?').bind(now(),b.id,now());}
 else throw new Fault(400,'Unsupported action.');
 const r=await db.batch([statement,auditStmt(db,u,action,action==='close-ballot'?b.id+': '+b.reason:b.id||b.principal)]);if(!r[0].meta.changes)throw new Fault(409,'The record no longer exists or has already changed.');return reply({ok:true});
 }catch(e){return error(e);}}
